cocoahouse/cocoa/urls.py
from django.urls import path, register_converter, include
from cocoa import views, converters
from django.contrib import admin

# ✅ Импорт для медиа-файлов:
from django.conf import settings
from django.conf.urls.static import static

from cocoahouse import settings

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Кафе, специализированное на какао COCOAHOUSE"

register_converter(converters.MonthConverter, "month")

urlpatterns = [
    path('', views.CocoaHome.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('catalog/', views.catalog, name='catalog'),
    path('contact/', views.contact, name='contact'),
    path('seasons/', views.seasons, name='seasons'),
    path('login/', views.login, name='login'),
    path('tag/<slug:tag_slug>/', views.show_tag_postlist, name='tag'),
    path('category/<slug:cat_slug>/',views.CocoaCategory.as_view(), name='category'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('addpage/', views.AddPage.as_view(), name='addpage'),
    path('edit/<int:pk>/', views.UpdatePage.as_view(),name='edit_page'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(),name='edit_page'),
    path('delete/<int:pk>', views.DeletePage.as_view(), name='delete_post'),


    path('cacao/', views.category_cacao, name='category_cacao'),
    path('hot-drinks/', views.category_hot_drinks, name='category_hot_drinks'),
    path('cold-drinks/', views.category_cold_drinks, name='category_cold_drinks'),
    path('baking/', views.category_baking, name='category_baking'),
    path('desserts/', views.category_desserts, name='category_desserts'),
    path('merch/', views.category_merch, name='category_merch'),
    path('gift-sets/', views.category_gift_sets, name='category_gift_sets'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cocoahouse/cocoahouse/urls.py
from cocoa import views

from django.contrib import admin
from django.urls import path, include

from cocoa.views import page_not_found

handler404 = page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cocoa.urls')),
    path('users/', include('users.urls',namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
]

cocoahouse/cocoa/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

from cocoahouse import settings


# Create your models here.

class Category(models.Model):
 name = models.CharField(max_length=100, db_index=True, verbose_name="Категория")
 slug = models.SlugField(max_length=255, unique=True, db_index=True)

 def __str__(self):
  return self.name

 def get_absolute_url(self):
  return reverse('tag', kwargs={'tag_slug': self.slug})

 class Meta:
  verbose_name = 'Категория'
  verbose_name_plural = 'Категории'

class PublishedModel(models.Manager):
 def get_queryset(self):
  return super().get_queryset().filter(is_published=Post.Status.PUBLISHED)

def translit_to_eng(s: str) -> str:
 d = {'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д':'d','е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и':'i', 'к': 'k','л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п':'p', 'р': 'r','с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х':'h', 'ц': 'c', 'ч': 'ch','ш': 'sh', 'щ': 'shch', 'ь': '', 'ы': 'y','ъ': '', 'э': 'r', 'ю': 'yu', 'я': 'ya'}
 return "".join(map(lambda x: d[x] if d.get(x,False) else x, s.lower()))

class Post(models.Model):
 tags = models.ManyToManyField('TagPost', blank=True,related_name='tags')

 class Status(models.IntegerChoices):
  DRAFT = 0, 'Черновик'
  PUBLISHED = 1, 'Опубликовано'

 title = models.CharField(max_length=255,verbose_name="Заголовок")
 slug = models.SlugField(max_length=255, db_index=True, unique=True)
 content = models.TextField(blank=True, verbose_name="Текст статьи")
 time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
 time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
 is_published = models.BooleanField(choices=tuple(map(lambda x:(bool(x[0]), x[1]), Status.choices)), default=Status.DRAFT, verbose_name="Статус")
 objects = models.Manager()
 published = PublishedModel()
 cat = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='posts', verbose_name="Категории")
 filial = models.OneToOneField('Filial', on_delete=models.SET_NULL, null=True, blank=True, related_name='Филиал')
 photo = models.FileField(upload_to="photos/%Y/%m/%d/", default=None, blank=True, null=True, verbose_name="Фото")
 author = models.ForeignKey(get_user_model(),on_delete=models.SET_NULL, related_name='posts',null=True, default=None)
 likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_posts', blank=True)

 def total_likes(self):
  return self.likes.count()

 class Meta:
  verbose_name = 'Посты'
  verbose_name_plural = 'Посты'
  ordering = ['-time_create']
  indexes = [
   models.Index(fields=['-time_create']),
  ]

 def __str__(self):
  return self.title

 def get_absolute_url(self):
  return reverse('post', kwargs={'post_slug':self.slug})

 def save(self, *args, **kwargs):
  transliterated = translit_to_eng(self.title)
  self.slug = slugify(transliterated)
  super().save(*args, **kwargs)


class Comment(models.Model):
 post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
 author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
 body = models.TextField()
 created = models.DateTimeField(auto_now_add=True)

class TagPost(models.Model):
 tag = models.CharField(max_length=100,db_index=True)
 slug = models.SlugField(max_length=255,unique=True)

 def get_absolute_url(self):
  return reverse('tag', kwargs={'tag_slug': self.slug})
 def __str__(self):
  return self.tag

class Filial(models.Model):
  address = models.CharField(max_length=100)
  month = models.IntegerField(null=True)

  def __str__(self):
   return self.address

class UploadFiles(models.Model):
 file = models.FileField(upload_to='uploads_model')

cocoahouse/cocoa/forms.py
from django import forms
from django.utils.deconstruct import deconstructible
from django.core.exceptions import ValidationError

from .models import Category, Filial, Post
from django.core.validators import MinLengthValidator,MaxLengthValidator

def clean_title(self):
 title = self.cleaned_data['title']
 ALLOWED_CHARS = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯабвгдеёжзийклмнопрстуфхцчшщбыъэюя0123456789- "
 if not (set(title) <= set(ALLOWED_CHARS)):
     raise ValidationError("Должны быть только русские символы, дефис и пробел.")
 return title


class AddPostForm(forms.ModelForm):
    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 50:
            raise ValidationError('Длина превышает 50 символов')
        return title

    cat = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Категория не выбрана", label="Категории")
    filial = forms.ModelChoiceField(queryset=Filial.objects.all(),required=False, empty_label="Нет филиала", label="Филиал")
    class Meta:
        model = Post
        fields = ['title', 'slug', 'content', 'photo', 'is_published', 'cat', 'filial', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
        }

class UploadFileForm(forms.Form):
 file = forms.FileField(label="Файл")

cocoahouse/cocoa/views.py
from calendar import month
from datetime import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.template.loader import render_to_string
from django.core.exceptions import ValidationError
import uuid
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy

from cocoa.forms import AddPostForm, UploadFileForm
from cocoa.models import Post, Category, TagPost, Filial, UploadFiles
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.views.generic.edit import DeleteView
from django.core.paginator import Paginator

from cocoa.utils import DataMixin
from users.forms import CommentForm

main_menu = [{'title': "О сайте", 'url_name': 'about'},
 {'title': "Каталог", 'url_name': 'catalog'},
 {'title': "Сезонное меню", 'url_name': 'seasons'},
 {'title': "Обратная связь", 'url_name': 'contact'},
 {'title': "Добавить пост", 'url_name': 'addpage'}
]
class CocoaHome(DataMixin, ListView):
    template_name = 'cocoa/index.html'
    context_object_name = 'posts'
    #paginate_by = 3

    def get_context_data(self, *, object_list=None,**kwargs):
        return self.get_mixin_context(super().get_context_data(**kwargs), title = 'Главная страница',cat_selected = 0,)

    def get_queryset(self):
        return Post.published.all().select_related('cat')

class CocoaCategory(DataMixin, ListView):
    template_name = 'cocoa/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = context['posts'][0].cat
        return self.get_mixin_context(context, title='Категория - ' + cat.name, cat_selected = cat.id,)

    def get_queryset(self):
        return Post.published.filter(cat__slug=self.kwargs['cat_slug']).select_related('cat')

def handle_uploaded_file(f):
    name = f.name
    ext = ''
    if '.' in name:
        ext = name[name.rindex('.'):]
        name = name[:name.rindex('.')]
        suffix = str(uuid.uuid4())
    with open(f"uploads/{name}_{suffix}{ext}", "wb+") as destination:
        for chunk in f.chunks():
            destination.write(chunk)

@login_required
def about(request):
    contact_list = Post.published.all()
    paginator = Paginator(contact_list, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if request.method == "POST":
        form = UploadFileForm(request.POST,request.FILES)
        if form.is_valid():
            fp = UploadFiles(file=form.cleaned_data['file'])
            fp.save()
    else:
        form = UploadFileForm()
    return render(request, 'cocoa/about.html', {'page_obj':page_obj, 'title': 'О сайте', 'main_menu': main_menu})

def catalog(request):
 return render(request, 'cocoa/catalog.html',{'title': 'Каталог', 'main_menu': main_menu})

def seasons(request):
 return HttpResponse("Сезонное меню")

@permission_required(perm='cocoa.view_cocoa', raise_exception=True)
def contact(request):
    return render(request, 'cocoa/contact.html', {
        'title': 'Обратная связь'
    })

def login(request):
 return HttpResponse("Вход в аккаунт")

class TagPostList(DataMixin, ListView):
    template_name = 'cocoa/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = TagPost.objects.get(slug=self.kwargs['tag_slug'])
        return self.get_mixin_context(context, title='Тег: ' + tag.tag)

    def get_queryset(self):
        return Post.published.filter(tags__slug=self.kwargs['tag_slug']).select_related('cat')

class ShowPost(DataMixin, DetailView):
 model = Post
 template_name = 'cocoa/post.html'
 slug_url_kwarg = 'post_slug'
 context_object_name = 'post'

 def get_context_data(self, **kwargs):
     context = super().get_context_data(**kwargs)
     post = context['post']
     context = self.get_mixin_context(context, title=post.title)
     context['comments'] = post.comments.all().order_by('-created')
     context['form'] = CommentForm()
     context['liked'] = self.request.user in post.likes.all()
     return context

 def post(self, request, *args, **kwargs):
     self.object = self.get_object()
     post = self.object

     # Лайк
     if 'like' in request.POST:
         if request.user.is_authenticated:
             if request.user in post.likes.all():
                 post.likes.remove(request.user)
             else:
                 post.likes.add(request.user)
         return redirect('post', post_slug=post.slug)

     # Комментарий
     if 'comment' in request.POST:
         form = CommentForm(request.POST)
         if form.is_valid() and request.user.is_authenticated:
             comment = form.save(commit=False)
             comment.post = post
             comment.author = request.user
             comment.save()
         return redirect('post', post_slug=post.slug)

     return redirect('post', post_slug=post.slug)

 def get_object(self, queryset=None):
     return get_object_or_404(Post.published,slug=self.kwargs[self.slug_url_kwarg])

class AddPage(PermissionRequiredMixin, LoginRequiredMixin, DataMixin, FormView):
 form_class = AddPostForm
 template_name = 'cocoa/addpage.html'
 success_url = reverse_lazy('home')
 permission_required = 'cocoa.add_post'
 def form_valid(self, form):
     w = form.save(commit=False)
     w.author = self.request.user
     w.save()  # <--- вот этого не хватало
     return super().form_valid(form)


class UpdatePage(DataMixin, UpdateView):
 model = Post
 fields = ['title', 'content', 'photo', 'is_published', 'cat']
 template_name = 'cocoa/addpage.html'
 title_page = 'Редактирование статьи'
 success_url = reverse_lazy('home')

class DeletePage(DataMixin, DeleteView):
    model = Post
    template_name = 'cocoa/delete_confirm.html'
    success_url = reverse_lazy('home')

def show_tag_postlist(request, tag_slug):
    tag = get_object_or_404(TagPost, slug=tag_slug)
    posts = tag.tags.filter(is_published=Post.Status.PUBLISHED)
    data = {
        'title': f'Тег: {tag.tag}',
        'main_menu': main_menu,
        'posts': posts,
        'cat_selected': None,
    }
    return render(request, 'cocoa/index.html', context=data)


def menu(request):
    return HttpResponse(f"<h1>Меню</h1>")

#ТУТ НОВЫЕ
def category_cacao(request):
 return HttpResponse("Сорта какао")

def category_hot_drinks(request):
 return HttpResponse("Горячие напитки")

def category_cold_drinks(request):
 return HttpResponse("Холодные напитки")

def category_baking(request):
 return HttpResponse("Выпечка")

def category_desserts(request):
 return HttpResponse("Выпечка")

def category_merch(request):
 return HttpResponse("Мерч")

def category_gift_sets(request):
 return HttpResponse("Подарочные наборы")


def menu_slug(request,cat_slug):
    if request.GET:
        print(request.GET)
    if request.POST:
        print(request.POST)
    if cat_slug == 'main':
        return redirect ('home',permanent=True)
    return HttpResponse(f"<h1>Категории меню </h1><p >категория меню с названием:{ cat_slug }</p>")

def get_season(month):
    if month in [12, 1, 2]:
        return "зиму"
    elif month in [3, 4, 5]:
        return "весну"
    elif month in [6, 7, 8]:
        return "лето"
    elif month in [9, 10, 11]:
        return "осень"
    return "неизвестный сезон"

def season(request):
    current_month = datetime.now().month
    return redirect(reverse('season_menu', args=[current_month]))  # Перенаправляем на /season/<текущий_месяц>/

def season_menu(request, month):
    season = get_season(month)
    return HttpResponse(f"<h1>Сезонное меню на {season}</h1>")

def page_not_found(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

cocoahouse/cocoa/templates/cocoa/about.html
{% extends 'base.html' %}

{% block content %}

<style>
    .post-list {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 30px;
        margin: 40px auto;
        max-width: 800px;
    }

    .post-item {
        background-color: #fff8f0;
        border: 1px solid #e0d6c6;
        border-radius: 16px;
        padding: 25px 35px;
        width: 100%;
        box-shadow: 0 6px 12px rgba(0, 0, 0, 0.08);
        text-align: center;
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }

    .post-item:hover {
        transform: translateY(-4px);
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.12);
    }

    .post-item h2 {
        margin: 0;
        color: #000000;
        font-size: 28px;
        font-weight: bold;
    }

    .read-more-container {
        margin-top: 20px;
        display: flex;
        justify-content: center;
    }

    .read-more {
        background-color: #3e2723;
        color: white;
        padding: 10px 24px;
        border-radius: 10px;
        text-decoration: none;
        font-size: 16px;
        transition: background-color 0.3s ease;
        font-weight: bold;
        border: none;
    }

    .read-more:hover {
        background-color: #5d4037;
    }

    .pagination {
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 12px;
        margin: 40px 0;
        flex-wrap: wrap;
    }

    .pagination a,
    .pagination .current {
        padding: 10px 20px;
        background-color: #3e2723;
        color: white;
        border-radius: 8px;
        text-decoration: none;
        font-weight: bold;
        font-size: 16px;
        transition: background-color 0.3s ease;
    }

    .pagination a:hover {
        background-color: #5d4037;
    }

    .pagination .current {
        background-color: #ffcc00;
        color: #3e2723;
    }

    h1 {
        text-align: center;
        margin-top: 20px;
        color: #3e2723;
        font-size: 48px;
        font-weight: bold;
    }
</style>

<h1>{{title}}</h1>

<div class="about-content">
    <p>Добро пожаловать на наш сайт! Мы — страстные поклонники какао, и наша цель — предоставить вам самые вкусные и качественные продукты из этого замечательного ингредиента.</p>

    <p>На нашем сайте вы найдете разнообразие какао-продуктов, от классических горячих напитков до эксклюзивных десертов и мерча, который порадует настоящих ценителей какао.</p>

    <p>Каждый продукт мы выбираем с особой тщательностью, чтобы обеспечить вам незабываемый вкус и уютные моменты, наслаждаясь любимым напитком. Мы стремимся сделать какао доступным и интересным для всех!</p>

    <p>Спасибо, что выбираете нас. Наслаждайтесь вкусом!</p>
</div>

<div class="post-list">
    {% for post in page_obj %}
        <div class="post-item">
            <h2>{{ post.title }}</h2>
            <div class="read-more-container">
                <a class="read-more" href="{% url 'post' post_slug=post.slug %}">Читать далее</a>
            </div>
        </div>
    {% endfor %}
</div>

<div class="pagination">
    {% for p in page_obj.paginator.page_range %}
        {% if p == page_obj.number %}
            <span class="current">{{ p }}</span>
        {% else %}
            <a href="?page={{ p }}">{{ p }}</a>
        {% endif %}
    {% endfor %}
</div>


{% endblock %}

cocoahouse/cocoa/templates/cocoa/addpage.html
{% extends 'base.html' %}
{% block content %}
<style>
  .submit-container {
    display: flex;
    justify-content: center;
    margin-top: 20px;
  }

  .submit-button {
    background-color: #3e2723; /* тёмно-коричневый, можешь заменить на black */
    color: white;
    font-size: 18px;
    padding: 12px 30px;
    border: none;
    border-radius: 30px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  .submit-button:hover {
    background-color: #4e342e; /* чуть светлее при наведении */
  }

  form {
    max-width: 600px;
    margin: 0 auto;
  }
</style>

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="submit-container">
    <button type="submit" class="submit-button">Добавить</button>
  </div>
</form>
{% endblock %}

cocoahouse/cocoa/templates/cocoa/catalog.html
{% extends 'base.html' %}
{% load menu_tags %}

{% block content %}
<h1 style="text-align: center;">{{ title }}</h1>

<div class="categories-centered">
    {% show_categorie %}
</div>
{% endblock %}

cocoahouse/cocoa/templates/cocoa/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Обратная связь</h1>

<p>Если у вас возникли вопросы, предложения или проблемы при использовании сайта, пожалуйста, воспользуйтесь следующей инструкцией:</p>

<ol>
    <li>Опишите вашу проблему как можно подробнее.</li>
    <li>Укажите, на какой странице сайта она возникла.</li>
    <li>Приложите скриншот, если это поможет лучше понять ситуацию.</li>
</ol>

<p>Свяжитесь с нами по электронной почте: <a href="mailto:support@cocoahouse.ru">support@cocoahouse.ru</a></p>

<p>Мы ответим вам в течение 1–2 рабочих дней.</p>
{% endblock %}

cocoahouse/cocoa/templates/cocoa/delete_confirm.html
{% extends 'base.html' %}
{% block content %}
  <h2>{{ title }}</h2>
  <p>Вы уверены, что хотите удалить "{{ object.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="submit-button">Удалить</button>
    <a href="{% url 'home' %}">Отмена</a>
  </form>
{% endblock %}

cocoahouse/cocoa/templates/cocoa/index.html
{% extends 'base.html' %}
{% block content %}
{% include 'cocoa/includes/nav.html' %}
{% load static %}

<h1>{{ title }}</h1>
<ul>
  {% for p in posts %}
    <li>
      <div class="article-panel">
        <p class="first">Категория: {{p.cat.name}} | автор: {{p.author.username|default:"неизвестен"}}</p>
        <p class="last">Дата: {{ p.time_update|date:"d-m-Y H:i:s" }}</p>
      </div>

      <h2>{{ p.title }}</h2>
      {% if p.photo %}
        <p ><img class="img-article-leftthumb" src="{{p.photo.url}}" style="max-width: 300px; height: auto; border-radius: 5px;"></p>
        {% endif %}
      <p>
        {% autoescape off %}
          {{ p.content|linebreaks|truncatewords:50 }}
        {% endautoescape %}
      </p>

      <p class="link-readpost"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
      <p>Адрес: {{ p.filial.address }}</p>
      <p>Действует до: {{ p.filial.month }}.2025</p>

    </li>
  {% endfor %}

</ul>

<nav class="list-pages">
  <ul>
    {% if page_obj.has_previous %}
      <li class="page-num">
        <a href="?page={{ page_obj.previous_page_number }}">← Назад</a>
      </li>
    {% endif %}

    {% for p in paginator.page_range %}
      {% if page_obj.number == p %}
        <li class="page-num page-num-selected">{{ p }}</li>
      {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
        <li class="page-num">
          <a href="?page={{ p }}">{{ p }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-num">
        <a href="?page={{ page_obj.next_page_number }}">Вперёд →</a>
      </li>
    {% endif %}
  </ul>
</nav>


<img src="{% static 'cocoa/images/badian.png' %}" alt="Бадьян" class="badian">
{% include 'cocoa/includes/nav.html' %}
{% endblock %}

cocoahouse/cocoa/templates/cocoa/list_categories.html
{% for cat in cats %}
 {% if cat.id == cat_selected %}
 <li
class="selected">{{cat.name}}</li>
 {% else %}
 <li><a href="{{ cat.get_absolute_url
}}">{{cat.name}}</a></li>
 {% endif %}
{% endfor %}

cocoahouse/cocoa/templates/cocoa/list_tags.html
{% if tags %}

 Теги:</p>
 <ul class="tags-list">
 {% for t in tags %}
 <li><a
href="{{t.get_absolute_url}}">{{t.tag}}</a></li>
 {% endfor %}
 </ul>
{% endif %}

cocoahouse/cocoa/templates/cocoa/post.html
{% extends 'base.html' %}

{% block breadcrumbs %}
{% if perms.cocoa.change_post %}
<p><a href="{% url 'edit_page' post.slug %}">Редактировать</a></p>
{% endif %}
{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>

{% if post.photo %}
<p><img class="img-article-left" src="{{ post.photo.url }}" style="max-width: 400px; height: auto; border-radius: 5px;"></p>
{% endif %}

<p>{{ post.content|linebreaks }}</p>

<!-- Лайк -->
<form method="post">
    {% csrf_token %}
    <button type="submit" name="like">
        {% if liked %}
            ❤️ Убрать лайк
        {% else %}
            🤍 Поставить лайк
        {% endif %}
        ({{ post.total_likes }})
    </button>
</form>

<hr>

<!-- Комментарии -->
<h2>Комментарии</h2>
{% for comment in comments %}
    <p><strong>{{ comment.author }}</strong> — {{ comment.created|date:"d.m.Y H:i" }}<br>
    {{ comment.body }}</p>
{% empty %}
    <p>Комментариев пока нет.</p>
{% endfor %}

{% if user.is_authenticated %}
<h3 style="text-align: center;">Оставить комментарий</h3>

<form method="post" style="max-width: 600px; margin: 0 auto;">
    {% csrf_token %}
    <div>
        <label for="{{ form.body.id_for_label }}">Текст комментария</label><br>
        {{ form.body }}
    </div>
    <div style="text-align: center; margin-top: 10px;">
        <button type="submit" name="comment">Отправить комментарий</button>
    </div>
</form>
{% else %}
<p><a href="{% url 'login' %}?next={{ request.path }}">Войдите</a>, чтобы оставить комментарий.</p>
{% endif %}
{% endblock %}