cocoahouse/cocoa/urls.py
from django.urls import path, register_converter, include
from cocoa import views, converters
from django.contrib import admin

# ✅ Импорт для медиа-файлов:
from django.conf import settings
from django.conf.urls.static import static

from cocoahouse import settings

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Кафе, специализированное на какао COCOAHOUSE"

register_converter(converters.MonthConverter, "month")

urlpatterns = [
    path('', views.CocoaHome.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('catalog/', views.catalog, name='catalog'),
    path('contact/', views.contact, name='contact'),
    path('seasons/', views.seasons, name='seasons'),
    path('login/', views.login, name='login'),
    path('tag/<slug:tag_slug>/', views.show_tag_postlist, name='tag'),
    path('category/<slug:cat_slug>/',views.CocoaCategory.as_view(), name='category'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('addpage/', views.AddPage.as_view(), name='addpage'),
    path('edit/<int:pk>/', views.UpdatePage.as_view(),name='edit_page'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(),name='edit_page'),
    path('delete/<int:pk>', views.DeletePage.as_view(), name='delete_post'),


    path('cacao/', views.category_cacao, name='category_cacao'),
    path('hot-drinks/', views.category_hot_drinks, name='category_hot_drinks'),
    path('cold-drinks/', views.category_cold_drinks, name='category_cold_drinks'),
    path('baking/', views.category_baking, name='category_baking'),
    path('desserts/', views.category_desserts, name='category_desserts'),
    path('merch/', views.category_merch, name='category_merch'),
    path('gift-sets/', views.category_gift_sets, name='category_gift_sets'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cocoahouse/cocoahouse/urls.py
from cocoa import views

from django.contrib import admin
from django.urls import path, include

from cocoa.views import page_not_found

handler404 = page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cocoa.urls')),
    path('users/', include('users.urls',namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
]

cocoahouse/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
 PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
 path('login/', views.LoginUser.as_view(),name='login'),
 path('logout/', LogoutView.as_view(),name='logout'),
 path('register/', views.RegisterUser.as_view(),name='register'),
 path('profile/',views.ProfileUser.as_view(), name='profile'),
path('users/profile/<int:pk>/', views.ProfileUser.as_view(), name='profile'),
 path('password-change/',views.UserPasswordChange.as_view(),name='password_change'),
 path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
 path('password-reset/',PasswordResetView.as_view(template_name="users/password_reset_form.html",email_template_name="users/password_reset_email.html",success_url=reverse_lazy("users:password_reset_done")),name='password_reset'),
 path('password-reset/done/',PasswordResetDoneView.as_view(template_name ="users/password_reset_done.html"),name='password_reset_done'),
 path('password-reset/<uidb64>/<token>/',PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",success_url=reverse_lazy("users:password_reset_complete")),name='password_reset_confirm'),
 path('password-reset/complete/',PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),name='password_reset_complete'),
]

cocoahouse/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load cocoa_tags %}
{% load menu_tags %}
{% getcats as categories %}
{% get_menu as main_menu %}

<html>
<head>
    <link type="text/css" href="{% static 'cocoa/css/styles.css' %}" rel="stylesheet" />
    <title>{{ title }}</title>
</head>
<body>

<div class="header">
   <ul id="mainmenu" class="mainmenu">
    <li class="logo">
        <a href="{% url 'home' %}">
            <img src="{% static 'cocoa/images/cocoa.png' %}" alt="Логотип" class="logo">
        </a>
    </li>

    <li><a href="{% url 'home' %}">Главная</a></li>

    {% for m in mainmenu %}
        <li><a href="{% url m.url_name %}">{{ m.title }}</a></li>
    {% endfor %}

    {% if user.is_authenticated %}
        <li class="last">
            <a href="{% url 'users:profile' %}">{{ user.username }}</a> |
            <form action="{% url 'users:logout' %}" method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit" style="background:none; border:none; padding:0; color:#ddd; cursor:pointer;">
                    Выйти
                </button>
            </form>
        </li>
    {% else %}
        <li class="last">
            <a href="{% url 'users:login' %}">Войти</a> |
            <a href="{% url 'users:register' %}">Регистрация</a>
        </li>
    {% endif %}
</ul>

    <div class="clear"></div>
</div>
{% block breadcrumbs %}{% endblock %}


{% block content %}
{% endblock %}

{% block navigation %}
{% endblock %}

<!-- Sidebar слева -->
<td valign="top" class="left-chapters">
    <ul id="leftchapters">
        {% if cat_selected == 0 or cat_selected is None %}
            <li class="selected">Все категории</li>
        {% else %}
            <li><a href="{% url 'home' %}">Все категории</a></li>
        {% endif %}
        {% show_categories cat_selected_id=cat_selected %}
        <li class="share">
            <p>Наш канал</p>
            <a class="share-yt" href="..." target="_blank" rel="nofollow"></a>
        </li>
        <li>{% show_all_tags %}</li>
    </ul>
</td>
<!-- Конец Sidebar'а -->

<!-- Футер -->
<footer class="footer">
    <div class="footer-container">
        <ul class="footer-categories">
            {% for cat in categories %}
                <li><a href="{% url 'category' cat.id %}">{{ cat.name }}</a></li>
            {% endfor %}
        </ul>
        <p>&copy; 2025 Cocoa House. Все права защищены.</p>
    </div>
</footer>

</body>
</html>